#server:
#  servlet:
#    context-path: /planservice
#  port: 8081
#spring:
#  application:
#    name: PLAN-SERVICE
#  datasource:
#    name: user
#    url: jdbc:mysql://localhost:3306/plan_service_2a
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#    show-sql: true
    
#  config:
#    import: optional:configserver:http//localhost:8085
    
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true


      
      